export function getRandomPersonName() {
  // Generate a random name from a first and last name (male and female).
  const firstNamesMale = [
    "James",
    "John",
    "Robert",
    "Michael",
    "William",
    "David",
    "Richard",
    "Charles",
    "Joseph",
    "Thomas",
    "Christopher",
    "Daniel",
    "Paul",
    "Mark",
    "Donald",
    "George",
    "Kenneth",
    "Steven",
    "Edward",
    "Brian",
    "Ronald",
    "Anthony",
    "Kevin",
    "Jason",
    "Matthew",
  ];
  const firstNamesFemale = [
    "Mary",
    "Patricia",
    "Linda",
    "Barbara",
    "Elizabeth",
    "Jennifer",
    "Maria",
    "Susan",
    "Margaret",
    "Dorothy",
    "Lisa",
    "Nancy",
    "Karen",
    "Betty",
    "Helen",
    "Sandra",
    "Donna",
    "Carol",
    "Ruth",
    "Sharon",
    "Michelle",
    "Laura",
    "Sarah",
    "Kimberly",
    "Deborah",
  ];
  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Jones",
    "Brown",
    "Davis",
    "Miller",
    "Wilson",
    "Moore",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
    "Thompson",
    "Garcia",
    "Martinez",
    "Robinson",
    "Clark",
    "Rodriguez",
    "Lewis",
    "Lee",
    "Walker",
    "Hall",
  ];
  // Get a random first name from the firstNames array.
  const firstName =
    Math.random() < 0.5
      ? firstNamesMale[Math.floor(Math.random() * firstNamesMale.length)]
      : firstNamesFemale[Math.floor(Math.random() * firstNamesFemale.length)];
  // Get a random last name from the lastNames array.
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
  // Return the full name.
  return {
    fullName: firstName + " " + lastName,
    firstName: firstName,
    lastName: lastName,
  };
}

export function getRandomCompanyName() {
  // Generate a random company name.
  const companyNames = [
    "Acme",
    "Alpha",
    "Ampersand",
    "Apple",
    "Asterisk",
    "Atari",
    "Atom",
    "Avocado",
    "Baboon",
    "Banana",
    "Bazooka",
    "Beetle",
    "Bison",
    "Blackberry",
    "Blueberry",
    "Boomerang",
    "Bumblebee",
    "Butterfly",
    "Cactus",
    "Candy",
    "Cantaloupe",
    "Carrot",
    "Cashew",
    "Caterpillar",
    "Cherry",
    "Chestnut",
    "Cockroach",
    "Coconut",
    "Cucumber",
    "Cupcake",
    "Dandelion",
    "Dragonfly",
    "Dorian",
    "Eagle",
    "Eggplant",
    "Elephant",
    "Elk",
    "Falcon",
    "Fig",
    "Firefly",
    "Flamingo",
    "Flower",
    "Gazelle",
    "Giraffe",
    "Grape",
    "Grapefruit",
    "Guava",
    "Hedgehog",
    "Honeydew",
    "Hornet",
    "Horse",
    "Hummingbird",
    "Hyena",
    "Iguana",
    "Jackal",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "Kiwi",
    "Koala",
    "Lemur",
    "Lemon",
    "Lettuce",
    "Lion",
    "Lobster",
    "Lollipop",
    "Lychee",
    "Macadamia",
    "Mango",
    "Mantis",
    "Melon",
    "Moose",
    "Mushroom",
    "Nectarine",
    "Octopus",
    "Olive",
    "Ostrich",
    "Oyster",
    "Panda",
    "Papaya",
    "Parrot",
    "Peach",
    "Pear",
    "Pineapple",
    "Pistachio",
    "Plum",
    "Pomegranate",
    "Pumpkin",
    "Quail",
    "Quince",
    "Rabbit",
    "Raccoon",
    "Raspberry",
    "Rhinoceros",
    "Rocket",
    "Salamander",
    "Salmon",
    "Scorpion",
    "Seahorse",
    "Sesame",
    "Shark",
    "Squid",
    "Strawberry",
    "Sunflower",
    "Swan",
    "Tangerine",
    "Tiger",
    "Turtle",
    "Walnut",
    "Watermelon",
    "Whale",
    "Wombat",
    "Yam",
    "Zebra",
  ];
  // Get a random company name from the companyNames array.
  // Return the company name.
  return companyNames[Math.floor(Math.random() * companyNames.length)];
}